---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: ENC(KDai+Hq1Qk+odiQOQO7sF/9y2kP6/voM/Iqu7R/iEc0=)
      port: 27017
      database: spring_chat
      username: ENC(geXy4NXdWspEa44JeX24Bw==)
      password: ENC(BCN7yw3+rmjFh2osdWTY+Ws8RIFpp87B)
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: spring_chat
      username: ENC(ZIeSB0azmX0DanW+PnxWsQ==)
      password: ENC(TGTV27qA6G1KCfKf+O25XK3PGUUSkQ/7)
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: ENC(ausCau/tT4Q5APe6zSc9vIx/Qr3gIvi3)
      port: 27017
      database: spring_chat
      username: ENC(ZIeSB0azmX0DanW+PnxWsQ==)
      password: ENC(TGTV27qA6G1KCfKf+O25XK3PGUUSkQ/7)
      authentication-database: admin