spring:
  profiles:
    active: local
    include:
      - security
      - domain-mongo
      - domain-redis
  application:
    name: module-sse
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: 182.218.242.146:13302
    consumer:
      group-id: 1
logging:
  config: classpath:log4j2-local.xml

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ENC(zqQCJXYAZHqCud3kx4OKkQFDMjiDaYjpdyvPI9dB2HY=)
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
logging:
  config: classpath:log4j2-prod.xml
