spring:
  profiles:
    active: local
    include:
      - security
      - domain-mongo
      - domain-redis
  application:
    name: module-sse

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: ENC(Ztjw+261SOpHag+TEEAxpnYxczh99OIunHhyzzkWeMU=)
    consumer:
      group-id: 1
logging:
  config: classpath:log4j2-local.xml

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ENC(Ztjw+261SOpHag+TEEAxpnYxczh99OIunHhyzzkWeMU=)
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
logging:
  config: classpath:log4j2-prod.xml