---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ENC(gU9ZfcoDfB7XWEHHAK751d8V5V3H0cZVrWW0X0WscgA=)
      port: 6379

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis
      port: 6379
