spring:
  application:
    name: module-api
  profiles:
    active: local
    include:
      - domain-rdb
      - domain-mongo
      - domain-redis
      - security

cloud:
  aws:
    s3:
      bucket: spring-10k-chat
      region.static: ENC(eyAxwZTCHN/KiMWbgJmTPZQSnAkCDIa8)
      stack.auto: false
      credentials:
        access-key: ENC(xXPKI63zuX3jIdWEiDL1j6iGHop4DgPHY4nt8DEniU0=)
        secret-key: ENC(+1ajM+OvZkkPTPQpkG78NN4ZF39KxyGtlKwhiV6xnsyx+CSN6bVe8F+7z2NDVEzwBTOyu2wa0eI=)
      url: ENC(eeU7dYD35Y/adW5aDygBUlGybzwQCtEgq7Dc95shULWcfX4r0ffyBiAISNiRQmC3Px8m6qp8OpAcAVldfeZ0oQ==)
file:
  image-extensions: jpg,jpeg,png,heic
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
logging:
  config: classpath:log4j2-local.xml

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  config: classpath:log4j2-prod.xml