spring:
  application:
    name: module-api
  profiles:
    active: local
    include:
      - domain-rdb
      - domain-mongo
      - domain-redis
      - security
management:
  endpoints:
    web:
      exposure:
        include: "*"
cloud:
  aws:
    s3:
      bucket: potato-chat
      region.static: ENC(eyAxwZTCHN/KiMWbgJmTPZQSnAkCDIa8)
      stack.auto: false
      credentials:
        access-key: ENC(Euo0fKfkIyKwSmWr+UYtfOepuFGuvBdqPoWG17nsVgA=)
        secret-key: ENC(f14i18CHha0ifgNlkbUE9TC5HHAuRSH/bcmjdpKwnl6XALO0sZ/r5VYezmrBTdWfN6FFkJI8+18=)
      url: ENC(bApAIZwaT5LDwwX2o+iOr7sZDpcHrdZMJ25MieVb8WgNsHYKug0NIixLmiMkJlZjm411OlsJtkGSYcoXBk5kTQ==)
file:
  image-extensions: jpg,jpeg,png,heic
  image-size: 5 # MB
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
logging:
  config: classpath:log4j2-local.xml

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  config: classpath:log4j2-prod.xml