---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(5zYUJ18CPJVF0dlQXNLbJW+mSbpNnTQWPswytgK5UnOae3tXyPZoW47c6WGJwQeRhc3PB9TyGoWJVKTxtZ/B/g==)
    username: ENC(C8kPShYZA2ZUpvbtfkc9tw==)
    password: ENC(E3ilMLgprUS8Apss7J1DkQ==)

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://spring-10k-chat-mariadb:3306/spring_chat
    username: ENC(P1mw77NRdEklo0qiJrh12w==)
    password: ENC(jBD9AnaTXF8uOEyoYRGNyg==)