services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        restart: always
        volumes:
            - /containers/data/prometheus/config:/etc/prometheus
            - /containers/data/prometheus/data:/prometheus
        command:
            - '--storage.tsdb.path=/prometheus'
            - '--config.file=/etc/prometheus/prometheus.yaml'
        networks:
            - spring-10k-chat-network

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3001:3000"
        restart: always
        volumes:
            - /containers/grafana/data:/var/lib/grafana
            - /containers/grafana/provisioning/:/etc/grafana/provisioning/
        networks:
            - spring-10k-chat-network
        depends_on:
            - prometheus

    cadvisor:
        image: gcr.io/cadvisor/cadvisor
        container_name: cadvisor
        ports:
            - "13304:8080"
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        networks:
            - spring-10k-chat-network

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        ports:
            - "9100:9100"
        restart: always
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        networks:
            - spring-10k-chat-network

    loki:
        image: grafana/loki:latest
        container_name: loki
        ports:
            - "3100:3100"
        restart: always
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - /containers/data/loki/data:/loki
            - /containers/data/loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
        networks:
            - spring-10k-chat-network

networks:
    spring-10k-chat-network:
        external: true
