global:
    scrape_interval: 1s

scrape_configs:
    -   job_name: 'monitoring-item'
        scrape_interval: 1s
        scrape_timeout: 1s
        metrics_path: '/metrics'
        scheme: 'http'

        static_configs:
            -   targets: [ 'prometheus:9090', 'node-exporter:9100', 'cadvisor:8080' ]
                labels:
                    service: 'monitor'