spring:
    application:
        name: spring-chat
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:13306/spring_chat
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
jwt:
    secret: yQ3dMfYIsS4f4D8/5bNSmH4G3u0shPhiZa4NUsuQh1E=
    token-expiration: 180000
