spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:33306/spring_chat
        username: root
        password: 1234
    rabbitmq:
        username: admin
        password: 1234
        host: localhost
        port: 5672
        stomp-port: 61613
notification:
    queue-number: 1
