spring:
    config:
        activate:
            on-profile: test
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://spring-10k-chat-mariadb:3306/spring_chat
        username: root
        password: 1234
        p6spy:
            enabled: false
    data:
        mongodb:
            uri: mongodb://root:root!))$@mongodb:27017/spring_chat?authSource=admin
    jpa:
        properties:
            hibernate:
                show_sql: false