spring:
    config:
        activate:
            on-profile: test
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://spring-10k-chat-mariadb:3306/spring_chat
        username: root
        password: 1234
        p6spy:
            enabled: false
    jpa:
        properties:
            hibernate:
                show_sql: false
    rabbitmq:
        username: admin
        password: 1234
        host: rabbitmq
        port: 5672
        stomp-port: 61613
notification:
    queue-number: ${NOTIFICATION_QUEUE_NUMBER}
