spring:
    config:
        activate:
            on-profile: test
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://spring-10k-chat-mariadb:3306/spring_chat
        username: root
        password: 1234
        p6spy:
            enabled: false
    data:
        mongodb:
            host: mongodb
            port: 27017
            database: spring_chat
            username: root
            password: root!))$
            authentication-database: admin
    jpa:
        properties:
            hibernate:
                show_sql: false
    kafka:
        bootstrap-servers: 182.218.242.146:13302
        consumer:
            group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
