---
spring:
  config:
    activate:
      on-profile: local
jwt:
  secret: yQ3dMfYIsS4f4D8/5bNSmH4G3u0shPhiZa4NUsuQh1E=
  token-expiration: 180000

---
spring:
  config:
    activate:
      on-profile: prod
jwt:
  secret: yQ3dMfYIsS4f4D8/5bNSmH4G3u0shPhiZa4NUsuQh1E=
  token-expiration: 1800
